"""Pre-parse lint for common non-Aether syntax generated by AI models.

The parser stays small and deterministic. This pass runs before parsing in
CLI/SDK paths and turns frequent wrong-language forms into repairable,
structured diagnostics.
"""

from __future__ import annotations

import re
from typing import Iterable, List, Optional, Tuple

from .diagnostics import Diagnostic, Position


def lint_common_ai_syntax(source: str, filename: str = "<input>") -> List[Diagnostic]:
    """Return diagnostics for syntax that is known to be unsupported."""
    del filename
    diagnostics: List[Diagnostic] = []
    for line_number, raw_line in enumerate(source.splitlines(), start=1):
        line = _mask_strings(_strip_line_comment(raw_line))
        checks: Iterable[Tuple[Optional[re.Match[str]], str, str, str]] = (
            (
                re.search(r"\bfn\s+[A-Za-z_]", line),
                "E0001",
                "Aether uses `function`, not `fn`.",
                "replace `fn` with `function`",
            ),
            (
                re.search(r"->", line),
                "E0002",
                "Aether uses `returns`, not `->`.",
                "write `function f(x: Int) returns Int`",
            ),
            (
                re.search(r"\b(List|Map|Set|Option|Result)\s*\[", line),
                "E0003",
                "Aether generic types use angle brackets, such as `List<Int>`.",
                "replace square brackets in type syntax with angle brackets, for example `List<Int>`",
            ),
            (
                re.search(r"\.\s*len\s*\(\s*\)", line),
                "E0004",
                "Aether uses `length(xs)`, not `xs.len()`.",
                "replace method-style length calls with `length(value)`",
            ),
            (
                re.search(r"=>", line),
                "E0005",
                "Aether does not support JavaScript lambdas.",
                "write a named helper function instead of `(x) => ...`",
            ),
            (
                re.search(r"\.\s*(append|push)\s*\(", line),
                "E0009",
                "Aether does not support method-style list append or push.",
                "use functional append syntax such as `append(xs, value)`",
            ),
            (
                re.search(r"\b[A-Za-z_][A-Za-z_0-9]*\s*\[[^\]]+\]\s*=(?!=)", line),
                "E0006",
                "Aether does not support list item assignment.",
                "build a new list with `append` or a helper such as `updateAt`",
            ),
            (
                _explicit_generic_call_match(line),
                "E0008",
                "Aether does not support explicit generic call syntax.",
                "call the function normally, for example `identity(5)`, and let Aether infer the type",
            ),
            (
                _brace_block_match(line),
                "E0007",
                "Aether uses `do`/`end` blocks, not braces.",
                "replace `{ ... }` control blocks with `then` or `do` plus `end`",
            ),
        )
        for match, code, message, suggestion in checks:
            if match is None:
                continue
            diagnostics.append(
                Diagnostic(
                    code=code,
                    category="parse",
                    severity="error",
                    message=message,
                    position=Position(line_number, match.start() + 1),
                    suggestion=suggestion,
                    confidence=1.0,
                    source_snippet=raw_line,
                )
            )
    return diagnostics


def _strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for i, ch in enumerate(line):
        if escaped:
            escaped = False
            continue
        if ch == "\\" and in_string:
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if not in_string and ch == "/" and i + 1 < len(line) and line[i + 1] == "/":
            return line[:i]
    return line


def _mask_strings(line: str) -> str:
    out: List[str] = []
    in_string = False
    escaped = False
    for ch in line:
        if escaped:
            out.append(" " if in_string else ch)
            escaped = False
            continue
        if ch == "\\" and in_string:
            out.append(" ")
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
            out.append(" ")
            continue
        out.append(" " if in_string else ch)
    return "".join(out)


def _brace_block_match(line: str) -> Optional[re.Match[str]]:
    return re.search(r"\b(function|if|elif|else|while|for|match)\b.*\{", line)


def _explicit_generic_call_match(line: str) -> Optional[re.Match[str]]:
    if line.lstrip().startswith("function "):
        return None
    return re.search(r"(?<!\.)\b[A-Za-z_][A-Za-z_0-9?!]*\s*<[^>\n]+>\s*\(", line)
